apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deploy
  labels:
    app: index
    env: green
    version: v2.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: index
      env: green
  template:
    metadata:
      labels:
        app: index
        env: green
        version: v2.0.0
    spec:
      containers:
      - name: indexapp
        image: us-central1-docker.pkg.dev/smart-seer-434509-i6/pccopdrwk3/indexapp:green
        ports:
        - containerPort: 80