apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy
  labels:
    app: index
    env: blue
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: index
      env: blue
  template:
    metadata:
      labels:
        app: index
        env: blue
        version: v1.0.0
    spec:
      containers:
      - name: indexapp
        image: us-central1-docker.pkg.dev/smart-seer-434509-i6/pccopdrwk3/indexapp:blue
        ports:
        - containerPort: 80